In [1]:
import numpy as np

In [3]:
array = np.array([15,20,30])
print(array)


[15 20 30]


In [7]:
array1= np.array([15,30,3,40,50,60,70,80,90,10,110,80,13,140,150])
print(array1.shape)

(15,)


In [8]:
arrayreshape = array1.reshape(5,3) 
print(arrayreshape)

[[ 15  30   3]
 [ 40  50  60]
 [ 70  80  90]
 [ 10 110  80]
 [ 13 140 150]]


In [9]:
print("shape: ",arrayreshape.shape) 
print("dimension: ",arrayreshape.ndim) 
print("data type: ",arrayreshape.dtype.name) 
print("size: ",arrayreshape.size) 
print("type",type(arrayreshape)) 

shape:  (5, 3)
dimension:  2
data type:  int32
size:  15
type <class 'numpy.ndarray'>


In [10]:
array1.ndim

1

In [11]:
array2= np.array([[10,20,30,40],[50,60,70,80],[9,10,11,12]]) 
print(array2)

[[10 20 30 40]
 [50 60 70 80]
 [ 9 10 11 12]]


In [13]:
zeros= np.zeros((1,6))
zeros[0,3]=5

print(zeros)

[[0. 0. 0. 5. 0. 0.]]


In [14]:
np.ones((1,2))

array([[1., 1.]])

In [33]:
g[::-1]

array([     7, 600000,  50000,   4000,    300,     20,      1])

In [34]:
r= np.array([[1,2,3,4],[6,7,8,9]])
r

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [35]:
g = array.ravel() 
print(g)

[1 9 7 4]


In [37]:
print(r[1,0:2])

[6 7]


In [38]:
a= np.array([[1,2],[3,4],[6,7],[8,9]])
a

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [40]:
array_transpose = array2.T
print(array_transpose)

[[10 50  9]
 [20 60 10]
 [30 70 11]
 [40 80 12]]


In [41]:
array_transpose = array2.T
print(array_transpose)

[[10 50  9]
 [20 60 10]
 [30 70 11]
 [40 80 12]]


In [43]:
array5.resize((2,4)) 
print(array5)

NameError: name 'array5' is not defined